/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ViewProfile } from "./ViewProfile";
export * as factories from "./factories";
export { ViewProfile__factory } from "./factories/ViewProfile__factory";
